title: Free For Geeks
description: Free resources for developers.
# theme: jekyll-theme-cayman
theme: jekyll-theme-architect
author: Juan Diaz
email: contact@jpdiaz.dev
twitter_username: 1diazdev
github_username: JuanPabloDiaz
