# Reference-project: https://github.com/NorthernBUG/northernbug.github.io
title: Testing Jekyll Theme
description: A test site for Jekyll theme
author: Juan Pablo Diaz
email: contact@jpdiaz.dev
website: https://jpdiaz.dev

# social links
twitter_username: JuanDiaz_427
github_username: juanPabloDiaz
linkedin_username: 1diazdev
# youtube_username: jekyll

google_analytics:

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - FullStackDeveloper/Css/README.md
  - FullStackDeveloper/Html/README.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
